### Numpy_Assignment_2::


#### Question:1
#### Convert a 1D array to a 2D array with 2 rows?
#### Desired output::
#### array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr1d=np.array([0, 1, 2, 3, 4,5, 6, 7, 8, 9])
arr2d= np.reshape(arr1d,(2,5))
arr2d


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Question:2
##### How to stack two arrays vertically?

##### Desired Output::
##### array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

In [2]:
x = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
y = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
np.vstack((x,y))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

#### Question:3
##### How to stack two arrays horizontally?
#####  Desired Output::
#####  array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [3]:
x = np.array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1]])
y= np.array([[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
np.vstack((x,y))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

#### Question:4
##### How to convert an array of arrays into a flat 1d array?
#####  Desired Output::
##### array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [4]:
x = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Question:5
##### How to Convert higher dimension into one dimension?
##### Desired Output::
##### array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [9]:
arr=np.array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Question:6
##### Convert one dimension to higher dimension?
##### Desired Output::
##### array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])

In [14]:
arr=np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
newarr=arr.reshape(5, 3)
newarr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

#### Question:7
##### Create 5x5 an array and find the square of an array?



In [20]:
arr=np.random.random((5,5))

np.square(arr)

array([[2.13840181e-01, 9.98171538e-04, 3.00877312e-01, 5.33639522e-01,
        1.24748982e-03],
       [2.81070780e-01, 4.13831576e-01, 1.52098559e-01, 4.95651976e-02,
        1.27193421e-01],
       [2.89431356e-02, 4.29681859e-02, 2.16996032e-02, 1.12653589e-02,
        4.33920400e-01],
       [3.41985344e-04, 1.41258585e-01, 2.25259038e-01, 2.83225804e-01,
        5.29551840e-02],
       [8.66217026e-02, 8.63802736e-01, 3.65480009e-01, 1.64891784e-01,
        3.42130157e-01]])

##### Question:8
##### Create 5x6 an array and find the mean?



In [22]:
arr=np.random.random((5,6))
print("Original array")
print(arr)
print("Mean")
np.mean(arr)

Original array
[[8.44390011e-01 1.83623942e-01 7.27371251e-01 6.45347344e-01
  5.42591186e-01 3.79471784e-01]
 [9.08134854e-01 1.92046485e-01 9.59657831e-01 3.79627679e-02
  4.60816379e-01 1.07389078e-01]
 [2.47430004e-01 9.59273338e-01 8.77699654e-01 7.41987309e-01
  4.76800478e-01 9.90244326e-01]
 [6.85996036e-01 2.27708274e-01 2.29955200e-01 6.19406057e-01
  8.26508939e-04 6.24064659e-01]
 [4.00464128e-01 7.93582966e-01 4.38417962e-01 1.28748972e-01
  5.57284842e-01 7.25210670e-01]]
Mean


0.5237968098000496

##### Question:9
##### Find the standard deviation of the previous array in Q8?


In [23]:
np.std(arr)

0.2944909298879927

##### Question:10
##### Find the median of the previous array in Q8?



In [24]:
np.median(arr)

0.5499380140676986

##### Question:11
##### Find the transpose of the previous array in Q8?


In [26]:
print("Original array")
print(arr)
newarr=arr.transpose()
newarr

Original array
[[8.44390011e-01 1.83623942e-01 7.27371251e-01 6.45347344e-01
  5.42591186e-01 3.79471784e-01]
 [9.08134854e-01 1.92046485e-01 9.59657831e-01 3.79627679e-02
  4.60816379e-01 1.07389078e-01]
 [2.47430004e-01 9.59273338e-01 8.77699654e-01 7.41987309e-01
  4.76800478e-01 9.90244326e-01]
 [6.85996036e-01 2.27708274e-01 2.29955200e-01 6.19406057e-01
  8.26508939e-04 6.24064659e-01]
 [4.00464128e-01 7.93582966e-01 4.38417962e-01 1.28748972e-01
  5.57284842e-01 7.25210670e-01]]


array([[8.44390011e-01, 9.08134854e-01, 2.47430004e-01, 6.85996036e-01,
        4.00464128e-01],
       [1.83623942e-01, 1.92046485e-01, 9.59273338e-01, 2.27708274e-01,
        7.93582966e-01],
       [7.27371251e-01, 9.59657831e-01, 8.77699654e-01, 2.29955200e-01,
        4.38417962e-01],
       [6.45347344e-01, 3.79627679e-02, 7.41987309e-01, 6.19406057e-01,
        1.28748972e-01],
       [5.42591186e-01, 4.60816379e-01, 4.76800478e-01, 8.26508939e-04,
        5.57284842e-01],
       [3.79471784e-01, 1.07389078e-01, 9.90244326e-01, 6.24064659e-01,
        7.25210670e-01]])


##### Question:12
##### Create a 4x4 an array and find the sum of diagonal elements?


In [28]:
arr4x4=np.random.random((4,4))
print(arr4x4)
sum=np.trace(arr4x4)
sum

[[0.96556827 0.21811599 0.9360516  0.8349666 ]
 [0.66103228 0.33953277 0.62648502 0.89734855]
 [0.27532567 0.42451085 0.02300772 0.98839571]
 [0.73207039 0.8364595  0.74496717 0.68012237]]


2.008231137179255

##### Question:13
##### Find the determinant of the previous array in Q12?



In [29]:
np.linalg.det(arr4x4)

0.041793461149055064

##### Question:14
##### Find the 5th and 95th percentile of an array?



In [31]:

print("5th percentile")
print(np.percentile(arr4x4,5))
print("95th percentile")
print(np.percentile(arr4x4,95))

5th percentile
0.16933892677912588
95th percentile
0.9712751330209237


##### Question:15
##### How to find if a given array has any null values?

In [43]:
a = np.array([1,2,3,np.nan])
np.isnan(a).any()

True